name = "ModelingToolkitStandardLibrary"
uuid = "16a59e39-deab-5bd0-87e4-056b12336739"
version = "2.25.0"
authors = ["Chris Rackauckas and Julia Computing"]

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
BSeries = "ebb8d67c-85b4-416c-b05f-5f409e808f32"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
IfElse = "615f187c-cbe4-4ef1-ba3b-2fcf58d6d173"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
PreallocationTools = "d236fae5-4411-538c-8e31-a6e3d9e00b46"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
ReservoirComputing = "7c2d2b1e-3dd4-11ea-355a-8f6a8116e294"
RootedTrees = "47965b36-3f3e-11e9-0dcf-4570dfd42a8c"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
WeightInitializers = "d49dbf32-c5c2-4618-8acc-27bb2598ef2d"

[sources.BSeries]
path = "/home/runner/work/cogpilot.jl/cogpilot.jl/BSeries.jl"

[sources.ReservoirComputing]
path = "/home/runner/work/cogpilot.jl/cogpilot.jl/ReservoirComputing.jl"

[sources.RootedTrees]
path = "/home/runner/work/cogpilot.jl/cogpilot.jl/RootedTrees.jl"

[compat]
ADTypes = "1"
Adapt = "4.4.0"
Aqua = "0.8"
BSeries = "0.1"
ChainRulesCore = "1.24"
Combinatorics = "1.0.3"
Compat = "4.18.1"
ControlSystemsBase = "1.4"
DataFrames = "1.7"
DataInterpolations = "6, 8"
DiffEqBase = "6.152"
ForwardDiff = "0.10"
IfElse = "0.1"
LaTeXStrings = "1.4.0"
Latexify = "0.16.10"
LinearAlgebra = "1.10"
ModelingToolkit = "10, 11"
NNlib = "0.9.31"
OrderedCollections = "1.8.1"
OrdinaryDiffEq = "6.87"
OrdinaryDiffEqDefault = "1.1"
Polynomials = "4.1.0"
PreallocationTools = "0.4.23"
Preferences = "1.5.0"
RecipesBase = "1.3.4"
Reexport = "1.2.2"
Requires = "1.3.1"
ReservoirComputing = "0.11, 0.12"
RootedTrees = "2"
SafeTestsets = "0.1"
SciMLStructures = "1.4.2"
SymbolicIndexingInterface = "0.3.28"
Symbolics = "6.14, 7"
Test = "1"
WeightInitializers = "1.2.2"
julia = "1.10"

[extras]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
ControlSystemsBase = "aaaaaaaa-a6ca-5380-bf3e-84a91bcd477e"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
OrdinaryDiffEqDefault = "50262376-6c5a-4cf5-baba-aaf4f84d72d7"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
SciMLStructures = "53ae85a6-f571-4167-b2af-e1d143709226"
SymbolicIndexingInterface = "2efcf032-c050-4f8e-a9bb-153293bab1f5"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ADTypes", "Aqua", "LinearAlgebra", "OrdinaryDiffEqDefault", "OrdinaryDiffEq", "SafeTestsets", "Test", "ControlSystemsBase", "DataFrames", "DataInterpolations", "SciMLStructures", "SymbolicIndexingInterface", "ForwardDiff"]
